# Generated by Django 5.2.7 on 2025-11-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_payment_stripe_session_id'),
        ('item', '0003_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
    ]
