# Generated by Django 5.2.7 on 2025-11-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_paymentitem_item_name_alter_paymentitem_item'),
        ('item', '0003_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
    ]
